# Generated by Django 4.1.3 on 2022-12-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_owner_question_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='owner',
            new_name='user',
        ),
    ]
